apiVersion: v1
kind: Namespace
metadata:
  name: redhat-nvidia-gpu-addon
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-nvidia-gpu-addon
  namespace: redhat-nvidia-gpu-addon
spec:
  targetNamespaces:
  - redhat-nvidia-gpu-addon
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nvidia-gpu-addon-operator
  namespace: redhat-nvidia-gpu-addon
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: nvidia-gpu-addon-operator
  source: nvidia-addon-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: nvidia-gpu-addon-operator.v99.0.0
  config:
    env:
    - name: GPUDIRECT_RDMA_ENABLED
      value: "true"
